package br.org.cac.cacmvmiddleware.modelo;

public interface Beneficiario {
	
	public String cd_pessoa="";
	public String nome="";
	public String nome_mae="";
	public String d_estado_civil="";
	public String d_sexo="";
	public String dt_nascimento="";
	public String dt_inscricao="";
	public String carteira_titular="";
	public String parentesco="";
	public String nome_pai="";
	public String cep="";
	public String numero_telefone_1="";
	public String numero_identidade="";
	public String orgao_identidade="";
	public String cpf="";
	public String descricao="";
	public String bairro="";
	public String id_plano="";
	public String cidade="";
	public String id_sigla_estado="";
	public String tipo_usuario="";
	public String id_banco="";
	public String nome_agencia="";
	public String id_agencia="";
	public String conta_corrente="";
	public String carteira="";
	public String id_cidade="";
	public String porta="";
	public String desc_complemento1="";
	public String cco="";
	public String dv_cco="";
	public String geraBoletoProprio="";
	public String id_natureza="";
	public String celular_1="";
	public String forma_pagamento="";
	public String dia_vencimento="";
    public String cns="";
    public String ordem_endereco="";
    public String numero_comando_titular="";
    public String id_empresa = "";
    public String sn_ativo = "";
    public String cdMatricula = "";
    public String enviado = "";
    public String id="";
  
    public String getNome();
    public void setNome(String nome); 
	public String getNome_mae();
	public void setNome_mae(String nome_mae);
	public String getD_estado_civil();
	public void setD_estado_civil(String d_estado_civil);
	public String getD_sexo();
	public void setD_sexo(String d_sexo);
	public String getDt_nascimento();
	public void setDt_nascimento(String dt_nascimento);
	public String getDt_inscricao();
	public void setDt_inscricao(String dt_inscricao);
	public String getCarteira_titular();
	public void setCarteira_titular(String carteira_titular);
	public String getParentesco();
	public void setParentesco(String parentesco);
	public String getNome_pai();
	public void setNome_pai(String nome_pai);
	public String getCep();
	public void setCep(String cep);
	public String getNumero_telefone_1();
	public void setNumero_telefone_1(String numero_telefone_1);
	public String getNumero_identidade();
	public void setNumero_identidade(String numero_identidade);
	public String getOrgao_identidade();
	public void setOrgao_identidade(String orgao_identidade);
	public String getCpf();
	public void setCpf(String cpf);
	public String getDescricao();
	public void setDescricao(String descricao);
	public String getBairro();
	public void setBairro(String bairro);
	public String getId_plano();
	public void setId_plano(String id_plano);
	public String getCidade();
	public void setCidade(String cidade);
	public String getId_sigla_estado();
	public void setId_sigla_estado(String id_sigla_estado);
	public String getTipo_usuario();
	public void setTipo_usuario(String tipo_usuario);
	public String getId_banco();
	public void setId_banco(String id_banco);
	public String getNome_agencia();
	public void setNome_agencia(String nome_agencia);
	public String getId_agencia();
	public void setId_agencia(String id_agencia);
	public String getConta_corrente();
	public void setConta_corrente(String conta_corrente);
	public String getCarteira();
	public void setCarteira(String carteira);
	public String getId_cidade();
	public void setId_cidade(String id_cidade);
	public String getPorta();
	public void setPorta(String porta);
	public String getDesc_complemento1();
	public void setDesc_complemento1(String desc_complemento1);
	public String getCco();
	public void setCco(String cco);
	public String getDv_cco();
	public void setDv_cco(String dv_cco);
	public String getGeraBoletoProprio();
	public void setGeraBoletoProprio(String geraBoletoProprio);
	public String getId_natureza();
	public void setId_natureza(String id_natureza);
	public String getCdPessoa();
	public void setCdPessoa(String cd_pessoa);
	public String getCelular_1();
	public void setCelular_1(String celular_1);
	public String getForma_pagamento();
	public void setForma_pagamento(String forma_pagamento);
	public String getDia_vencimento();
	public void setDia_vencimento(String dia_vencimento);
	public String getCns();
	public void setCns(String cns);
	public String getOrdem_endereco();
	public void setOrdem_endereco(String ordem_endereco);
	public String getNumero_comando_titular();
	public void setNumero_comando_titular(String numero_comando_titular);
	public String getId_empresa();
	public void setId_empresa(String id_empresa);
	public String getSn_ativo();
	public void setSn_ativo(String sn_ativo);
	public String getCdMatricula();
	public void setCdMatricula(String cdMatricula);
	public String getEnviado();
	public void setEnviado(String enviado);
	public String getId();
	public void setId(String id);		

}
